CREATE DATABASE IF NOT EXISTS o2o_hitch DEFAULT CHARACTER SET utf8mb4;
USE o2o_hitch;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id VARCHAR(64) NOT NULL UNIQUE,
  role VARCHAR(32) NOT NULL,
  nickname VARCHAR(64) NOT NULL,
  mobile VARCHAR(32) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS trips (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  trip_id VARCHAR(64) NOT NULL UNIQUE,
  passenger_id VARCHAR(64) NOT NULL,
  departure VARCHAR(128) NOT NULL,
  destination VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_id VARCHAR(64) NOT NULL UNIQUE,
  trip_id VARCHAR(64) NOT NULL,
  driver_id VARCHAR(64) NOT NULL,
  passenger_id VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
